build: fix gitlab doc generatioin

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,3 +9,26 @@ variables:
 
 .test-tags:
   - docker
+
+# Build with mkdocs and publish on gitlab pages the documentation.
+pages:
+  script:
+    - $TOX_EXE -e doc --notest
+    - conda activate .tox/doc
+    # By default gitlab does not fetch all branches,
+    # this could fail when $MIKE_BRANCH is not yet existing
+    # but mike will create it.
+    - git fetch origin $MIKE_BRANCH --depth=1 || true
+    - config_git_push
+    - mike deploy --branch $MIKE_BRANCH --push $MIKE_ARGS
+    - |
+      # When there is no doc yet, redirect to the docs of the develop branch.
+      if [[ $(mike list --remote origin --branch $MIKE_BRANCH) == $CI_DEFAULT_BRANCH ]]; then
+        mike set-default --branch $MIKE_BRANCH --push $CI_DEFAULT_BRANCH;
+      fi
+    - |
+      # For release versions, redirect to them.
+      if [[ -n $CI_COMMIT_TAG ]]; then
+        mike set-default --branch $MIKE_BRANCH --push latest;
+      fi
+    - git checkout $MIKE_BRANCH
